---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aojenkinsdemo
spec:
  replicas: 1
  selector:
    matchLabels:
     app: aojenkinsdemo
  template:
    metadata:
      annotations:
        traffic.sidecar.istio.io/excludeOutboundIPRanges: 0.0.0.0/0
      labels:
        app: aojenkinsdemo
    spec:
      containers:
      - image: paulbouwer/hello-kubernetes:1.5
        name: aojenkinsdemo
        imagePullPolicy: Always
        env:
        - name: REDEPLOY
          value: 'THIS_STRING_IS_REPLACED_DURING_BUILD'
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 500m
            memory: "700Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: aojenkinsdemoproduction
  labels:
    app: aojenkinsdemo
spec:
  selector:
    app: aojenkinsdemo
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
